import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Discover from '@/components/Discover'
import AboutMe from '@/components/AboutMe'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import MyKnowledges from '@/components/MyKnowledges'
import Footer from '@/components/Footer'
import { Fade } from "react-awesome-reveal";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fade direction="left" cascade>
        <Discover />
      </Fade>
      <Fade direction="left" cascade>
        <AboutMe />
      </Fade>
      <Fade direction="left" cascade>
        <MyKnowledges />
      </Fade>
      <Fade direction="left" cascade>
        <Projects />
      </Fade>
      <Fade direction="left" cascade>
        <Contact />
      </Fade>
      <Footer />
      {/* <Page /> */}
    </>
  )
}
